### ISSUE TITLE
IP cameras instead of pi's?

### ISSUE THREAD

**Issue by JVTEAM** [dataplayer12/homesecurity#4]
Are you able to use existing IP cameras instead of the RPI setup?  Also where is the setup details for the Jetson TX2 i.e where do I specify the IP addresses of the cameras?

**Comment by dataplayer12** [comment]
Hi @jvteam 

To answer your question, yes, we can use any IP camera. The settings are specified in lines 117-120 of 'jetsontx2/tx2_surveillance.py'

I'm sorry the settings are a bit hidden and having answered this question many times, I now realise I should make them more transparent. And by the way, you can run the code meant for tx2 on a nano as well.

**Comment by JVTEAM** [comment]
Interesting.   To run the tx2 code do you still use the bash script or just run the tx2 surveillance python?

**Comment by dataplayer12** [comment]
Yes, always use the bash script. Just specify the `$DEVICE` parameter in the script as tx2, even if you are running it on a nano (if you want to monitor mutiple cameras with a nano). I assume that you have already compiled the model for your particular jetson device, as described in the tx2 setup [instructions](https://github.com/dataplayer12/homesecurity/tree/master/jetsontx2).

**Comment by DennisFaucher** [comment]
@dataplayer12 rather than accept the http streaming video from your program running on a Pi, would it be possible to accept the rtsp streaming video from an IP camera? I use a Foscam. TIA.

Rather than:    url1='http://pi1.local:8000/stream.mjpg'
Use this:     url1='rtsp://dennis:password@192.168.86.42:88/videoMain'

I tried this and tx2_surveillance.py failed with errors.
============================================
[h264 @ 0x8cf3450] non-existing PPS 0 referenced
[h264 @ 0x8cf3450] decode_slice_header error
[h264 @ 0x8cf3450] no frame!
Running stream for  VideoStream object at url: rtsp://dennis:password@192.168.86.42:88/videoMain
Running stream for  VideoStream object at url: rtsp://dennis:password@192.168.86.42:88/videoMain
Running stream for  VideoStream object at url: rtsp://dennis:password@192.168.86.42:88/videoMain
INFO:__main__:loading TRT graph from pb: ./human_detection/ssd_mobilenet_v1_coco_trt.pb
Running stream for  VideoStream object at url: rtsp://dennis:password@192.168.86.42:88/videoMain
Traceback (most recent call last):
  File "jetsontx2/tx2_surveillance.py", line 155, in <module>
    main()
  File "jetsontx2/tx2_surveillance.py", line 130, in main
    trt_graph = load_trt_pb(pb_path)
  File "/home/jetson/homesecurity/jetsontx2/utils/od_utils.py", line 28, in load_trt_pb
    trt_graph_def.ParseFromString(pf.read())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
    self._preread_check()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ./human_detection/ssd_mobilenet_v1_coco_trt.pb; No such file or directory
FATAL: exception not rethrown
launch.sh: line 44: 30152 Aborted                 (core dumped) python3 jetsontx2/tx2_surveillance.py

**Comment by dataplayer12** [comment]
In the http video source I am using, I provide the address of the `.mjpg` stream. You might need to specify the extension of the stream after `...videoMain`. If that doesn't work, try to figure out the gstreamer pipeline of your rtsp stream and specify that to be the url. As an example, I found this example rtsp pipeline:
```Shell
"rtspsrc location=rtsp://ip_address/stream latency=0 ! decodebin ! videoconvert ! appsink"
```
on this [blog](https://qiita.com/stnk20/items/242e400853579d511ea3). Sorry, the blog post is in Japanese but you can find a large body of literature on gstreamer pipelines of rtsp streams in English.

**Comment by DennisFaucher** [comment]
Oh, that's brilliant. I did not realize that I could use gstreamer as the URL. That might work. 

How would I use one URL rather than four? Just replace url1,url2,url3,url4 with url1 in the function call? Thank you.

**Comment by dataplayer12** [comment]
Yes, you can just specify one url in the list that is input to `VideoStreamHandler` class.

**Comment by DennisFaucher** [comment]
Spent the day trying the get RTSP with gst-launch-1.0 working. Nothing yet. I _have_successfully redirected the rtsp feed to /dev/video1 on my Nano using ffmpeg. Can I use /dev/video1 as the camera input to jetsonano/securitycamnano.py? TIA

BTW, my working ffmpeg command is "ffmpeg -re -i rtsp://dennis:password@192.168.86.42:88/videoMain -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video1"

**Comment by dataplayer12** [comment]
Yes, you can just replace the gstpipeline in line 41 of securitycamnano.py to /dev/video1

I request you to please reopen this issue or begin a new one. It is difficult to respond to comments in closed issues, so the response gets delayed.

**Comment by DennisFaucher** [comment]
Thank you. Will do.
